/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewPack;

import javax.swing.ImageIcon;

/**
 *
 * This is the main menu.
 * <p>
 * This menu contains the setup information for the game board.
 * It is also the main navigation for the program.
 * @author tajac
 * 
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form HowToPlayMenu
     * sets default information for the player
     * just in case user does not.
     */
    public MainMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Trivial Delux");
        // set window icon:
        ImageIcon icon = new ImageIcon("src/viewPack/images/window_icon.png");
        this.setIconImage(icon.getImage());
        
        // Set default player stuff
        this.subjects[0] = 0;
        this.subjects[1] = 1;
        this.subjects[2] = 2;
        this.subjects[3] = 3;
        this.subjects[4] = 4;
        this.subjects[5] = 5;
        this.players[0] = "DefaultPlayer";
        this.numberPlayers = 1;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        start_bttn = new javax.swing.JButton();
        howToPlay_bttn = new javax.swing.JButton();
        options_bttn = new javax.swing.JButton();
        quit_bttn = new javax.swing.JButton();
        qdataBaseButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comfortaa Light", 0, 47)); // NOI18N
        jLabel1.setText("Trivial Delux 6 Piece Edition");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        start_bttn.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        start_bttn.setText("Start");
        start_bttn.setActionCommand("start_bttn");
        start_bttn.setName(""); // NOI18N
        start_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_bttnActionPerformed(evt);
            }
        });

        howToPlay_bttn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        howToPlay_bttn.setText("How to Play");
        howToPlay_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                howToPlay_bttnActionPerformed(evt);
            }
        });

        options_bttn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        options_bttn.setText("Options");
        options_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                options_bttnActionPerformed(evt);
            }
        });

        quit_bttn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        quit_bttn.setText("Quit");
        quit_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quit_bttnActionPerformed(evt);
            }
        });

        qdataBaseButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        qdataBaseButton.setText("Q Database");
        qdataBaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qdataBaseButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("start here -->");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(start_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(312, 312, 312))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(options_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(62, 62, 62)
                                    .addComponent(howToPlay_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(186, 186, 186))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(qdataBaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quit_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(123, 123, 123)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(start_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(howToPlay_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(options_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(quit_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qdataBaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        start_bttn.getAccessibleContext().setAccessibleDescription("Starts the game");
        howToPlay_bttn.getAccessibleContext().setAccessibleDescription("Instructions on how to play the game");
        options_bttn.getAccessibleContext().setAccessibleDescription("Adjust settings");
        quit_bttn.getAccessibleContext().setAccessibleDescription("Close the program");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * starts the game board
     * loads in the custom options
     * @param evt button pressed
     */
    // When the "Start" button is pressed:
    private void start_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_bttnActionPerformed
        // Start the game!
        GameBoard start = new GameBoard(this.subjects,this.players,this.numberPlayers);
        start.setVisible(true);
        this.setVisible(false);
        this.dispose();
        
        
    }//GEN-LAST:event_start_bttnActionPerformed

    /**
     * Exits the program
     * @param evt 
     */
    // When the "Quit" button is pressed:
    private void quit_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quit_bttnActionPerformed
        System.exit(0);     // terminate program
    }//GEN-LAST:event_quit_bttnActionPerformed

    /**
     * loads the how to play menu
     * @param evt when button is pressed
     */
    // When "How to Play" button is pressed:
    private void howToPlay_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_howToPlay_bttnActionPerformed
        // Open HowToPlayMenu Jform
        HowToPlayMenu h2p = new HowToPlayMenu(); 
        h2p.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_howToPlay_bttnActionPerformed

    /**
     * loads the options menu
     * @param evt when button is pressed
     */
    // When "options" button is pressed:
    private void options_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_options_bttnActionPerformed
        // show OptionsMenu Jform
        OptionsMenu options = new OptionsMenu();
        options.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_options_bttnActionPerformed
    /**
     * loads the database
     * @param evt button pressed
     */
    private void qdataBaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qdataBaseButtonActionPerformed
        // TODO add your handling code here:
        DatabaseViewer dbView = new DatabaseViewer();
        dbView.setVisible(true);
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_qdataBaseButtonActionPerformed
    /**
     * This function updates the information related to the board
     * @param newSubjects list of numbers relative to subjects
     * @param names list of names of players
     * @param amount amount of players 
     */
    public void setPlayerinfo(int [] newSubjects, String [] names, int amount)
    {
        
        int testForNull;
        // This will check for improper settings.
        try
        {
            testForNull = newSubjects[0];
            testForNull = newSubjects[1];
            testForNull = newSubjects[2];
            testForNull = newSubjects[3];
            testForNull = newSubjects[4];
            testForNull = newSubjects[5];
            this.subjects = newSubjects;
            if(!names[0].equals(""))
            {
            this.players = names;
            this.numberPlayers = amount;
            }
            
        }
        catch(Exception e)
        {
            // Will use default settings instead.
            this.setDefualt();
            
        }
        


    }
    private void setDefualt()
    {
        this.subjects[0] = 0;
        this.subjects[1] = 1;
        this.subjects[2] = 2;
        this.subjects[3] = 3;
        this.subjects[4] = 4;
        this.subjects[5] = 5;
        this.players[0] = "DefaultPlayer";
        this.numberPlayers = 1;
    }
    private int[] subjects = new int[6];
    private String[] players = new String[6];
    private int numberPlayers = 1;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton howToPlay_bttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton options_bttn;
    private javax.swing.JButton qdataBaseButton;
    private javax.swing.JButton quit_bttn;
    private javax.swing.JButton start_bttn;
    // End of variables declaration//GEN-END:variables
}
